version: '3'
volumes:
  dockerAngularSpringDatabaseData:
  nexus-data:
networks:
  monitor-net:
    external: true
services:
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: company
      MYSQL_USER: pradeep
      MYSQL_PASSWORD: pradeep
    ports:
      - 3307:3306
    volumes:
      - dockerAngularSpringDatabaseData:/var/lib/mysql
    networks:
      - monitor-net

  spring:
    container_name: devop-app
    image: oussamaboussetta/oussama_repo:latest
    restart: always
    depends_on:
      - database
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8082:8082"
    networks:
      - monitor-net

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - monitor-net
    restart: always

    #  mysql:
 #   container_name: mysql
  #  image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
#    command: --default-authentication-plugin=mysql_native_password
   # ports:
    #  - 3306:3306
#    restart: always
 #   environment:
  #    MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
   # networks:
    #  - monitor-net