version: '3'
networks:
  monitor-net:
    external: true
services:

  spring:
    container_name: devops-app
    image: oussamaboussetta/oussama_repo:latest
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - mysql
    networks:
      - monitor-net
  mysql:
    container_name: mysql
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - monitor-net